site_name: Backstage Metadata
site_description: "Backstage basic metadata, like templates, entites, etc."
repo_url: https://github.com/gianfragolo/backstage-metadata
edit_uri: edit/main/docs

nav:
  - "Home": "index.md"
  - "Code of Conduct": "CODE_OF_CONDUCT.md"

plugins:
  - techdocs-core
