apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
  - c#
  - aspnet
  - dotnet
  annotations:
    github.com/project-slug: gianfragolo/${{ values.repo_name }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
  links:
    - url: https://github.com/gianfragolo/${{ values.repo_name }}
      title: Github Repo
      icon: github
spec:
  type: website
  owner: group:${{ values.owner }}
  system: ${{ values.system }}
  lifecycle: experimental
  