name: pull-request
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  dotnet-ci:
    uses: gianfragolo/backstage-metadata/.github/workflows/dotnet-build-and-push.yml@main
    secrets: inherit
    with:
      component: ${{values.component_id|lower}}
      repoOwner: ${{values.repo_owner}}
      repoName: ${{values.repo_name}}
