apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - nodejs
  annotations:
    github.com/project-slug: gianfragolo/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/gianfragolo/${{ values.repo_name }}
      title: Github Repo
      icon: github
    - url: https://hub.docker.com/repository/docker/lucamilan/${{ values.component_id }}
      title: Dockerhub
      icon: docker
spec:
  type: service
  owner: group:${{ values.owner }}
  system: ${{ values.application }}
  lifecycle: experimental
  {%- if values.providesApi %}
  providesApis:
    {%- for api in values.providesApi.split(",") %}
    - ${{api | dump}}
    {%- endfor %}
  {%- endif %}
  {%- if values.dependsOn %}
  dependsOn:
    {%- for res in values.dependsOn.split(",") %}
    - resource:${{res}}
    {%- endfor %}
  {%- endif %}  