apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
    - nodejs
    - javascript
  annotations:
    github.com/project-slug: gianfragolo/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/gianfragolo/${{ values.repo_name }}
      title: Github Repo
      icon: github
  labels:
    environments: ${{values.environments.replaceAll(',','-')}}
spec:
  type: service
  owner: group:${{ values.owner }}
  system: ${{ values.application }}
  lifecycle: experimental
