apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id | dump }}
  description: ${{ values.description | dump }}
  tags:
    - api
    - rest
    - aspnet
  annotations:
    github.com/project-slug: gianfragolo/${{ values.repo_name }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.component_id }}
    backstage.io/kubernetes-namespace: lucamilan
  links:
    - url: https://github.com/gianfragolo/${{ values.repo_name }}
      title: Github Repo
      icon: github
    - url: https://cloud.okteto.com/#/spaces/lucamilan
      title: Okteto Platform
      icon: cloud      
    - url: https://${{ values.component_id }}-lucamilan.cloud.okteto.net/swagger
      title: Swagger
      icon: code
    - url: https://${{ values.component_id }}-lucamilan.cloud.okteto.net/swagger/v1/swagger.json
      title: API Spec
      icon: code
spec:
  type: openapi
  owner: group:${{ values.owner }}
  system: ${{ values.system }}
  lifecycle: experimental
  {%- if values.dependsOn %}
  dependsOn:
    {%- for res in values.dependsOn.split(",") %}
    - ${{res | dump}}
    {%- endfor %}
  {%- endif %}    
  # definition:
  #   $text: https://googlepay-lucamilan.cloud.okteto.net/swagger/v1/swagger.json
  definition: |
    {
    "openapi": "3.0.1",
    "info": {
      "title": ${{ values.name | dump }},
      "version": "1.0"
    },
    "paths": {
      "/Rest": {
        "get": {
          "tags": [
            "Rest"
          ],
          "operationId": "Get",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "string"
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "string"
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": { }
    }
