apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: gianfragolo/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:${{ values.owner }}
  system: ${{ values.system }}
  lifecycle: experimental
