site_name: ${{ values.name | dump }}
site_description: ${{ values.description | dump }}
repo_url: ${{ values.repo_url }}
edit_uri: edit/master/docs

nav:
  - "Home": "index.md"
  - "Getting Started": "getting-started.md"
  - "Code of Conduct": "CODE_OF_CONDUCT.md"
  - "Readme": "readme.md"

plugins:
  - techdocs-core
