name: "Build app ${{ values.name }}"

on:
  push:
    paths-ignore:
      - "docs/**"
      - "catalog-info.yaml"
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: yarn install
        run: |
          yarn install
