name: build and deploy a dotnet application
on:
  workflow_call:
    inputs:
      component:
        description: "The name of the .NET component this repo belongs to"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'A token passed from the caller workflow'
        required: true
      DOCKERHUB_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: set repo name
        shell: bash
        run: |
          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  push-image:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.component }}:latest
