name: build a dotnet application
on:
  workflow_call:
    inputs:
      component:
        description: "The name of the .NET component"
        required: true
        type: string
      repoOwner:
        description: "The name of the Owner"
        required: true
        type: string
      repoName:
        description: "The name of the Repository"
        required: true
        type: string

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: set repo name
        shell: bash
        run: |
          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  push-image:
    runs-on: ubuntu-latest
    needs: build-app
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: vars
        name: Set current Image TAG
        run: echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.component }}:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.component }}:${{ steps.vars.outputs.tag }}

      - name: Dispatch build image event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.repoOwner }}/${{ inputs.repoName }}
          event-type: build-image
          client-payload: '{ "tag": "${{ steps.vars.outputs.tag }}" }'